### ISSUE TITLE
Write a function to detect apogee

### ISSUE THREAD

**Issue by lo9key** [OregonStateRocketry/30k2018-CS-Capstone#19]
We need some kind of function or loop to detect apogee.  Feel free to edit or expand this list of requirements as you go.

- [x] Prevents accidental detection due to air pressure shockwaves
- [x] Able to read from the other sensor objects to get the data it needs

**Comment by ASladek** [comment]
Added a class with a method for apogee detection, but hasn't been tested with the sensor-reading code
b0c2cf691572c0f5628cda377f75e4c42aa649d1

**Comment by lo9key** [comment]
Allison's apogee method converted to a state machine in commit 4cc2ea2e76ac545df89556bb493fc17425537e36.
