### ISSUE TITLE
Add Flight Summary to GUI

### ISSUE THREAD

**Issue by ASladek** [OregonStateRocketry/30k2018-CS-Capstone#22]
Re-implement changes to app.js and add partials for summary page to allow viewing of flight data associated with a flight ID

**Comment by lo9key** [comment]
Good idea.  I lost track of what db data you need, so if you want help with the queries let's make a list here in the comments.

**Comment by lo9key** [comment]
@ASladek, here are the fields that I think you want.  Let me know if you need any other info:

![flight_table_query_3](https://user-images.githubusercontent.com/5560088/36758106-3cd72634-1bc8-11e8-928b-610a82f3b8f7.png)

(I still need to make the query available to the gui, but if this looks good I can have it up in the next day or two.)

**Comment by ASladek** [comment]
Implemented, but could use some visual adjustments
commit: bacb6e828fc2cf872e0a538c7a5add214bdfa0f5
