### ISSUE TITLE
Display - Graph tasks in progress

### ISSUE THREAD

**Issue by lo9key** [OregonStateRocketry/30k2018-CS-Capstone#31]
We need to make sure the display graphs and map are ready for expo.

Map ideas during 4/1 discussion:
- [x] Use different symbols for each callsign.
- [x] Symbols are in different colors to indicate altitude.
- [ ] Ensure we are ready to use maps at expo and test flight locations.

Graph ideas from 4/1 discussion:
- [ ] Make sure we can reach all graphs and map from website links
- [x] Verify altitude v time graph looks good.
- [x] Verify velocity v time graph looks good.
- [ ] (optional) Add acceleration v time.
- [ ] (optional) Add graphs for TeleMega.

Add any other outstanding graph issues that you know about.

**Comment by lo9key** [comment]
@revnak @ASladek Are we happy with the current state of the website?  If so, let's close this issue.

**Comment by revnak** [comment]
I’m happy
