### ISSUE TITLE
Refactor MPL3115A2 as a class

### ISSUE THREAD

**Issue by lo9key** [OregonStateRocketry/30k2018-CS-Capstone#8]
Let's refactor MPL3115A2 as a class so we can create it in the main program, and simply call something like mpl.read_alt() or mpl.read_temp() to get the appropriate values.

If it requires a delay, let's write a boolean mpl.is_ready() or similar, so that we can read the values when they are ready.

**Comment by revnak** [comment]
I setup a version of this which isn't quite a class but given that we aren't storing variables for it and we only have one on each board this should be sufficient. Individual functions can be called by including the document and referencing the function.

**Comment by lo9key** [comment]
It looks like it will stall until the sensor is ready to return a value.  Do we know how long that takes, or can we refactor to optionally return a value so the rest of the loop can continue?

Maybe we could use something like editing poll as:

```
def ready():
    # A lot of the top-level register variables aren't used, or could have shorter names
    return MPL3115A2_REGISTER_STATUS_PDR & bus.read_byte_data(MPL3115A2_ADDRESS, MPL3115A2_REGISTER_STATUS)
```

And all of the places that call poll:
```
if not ready():  return None
```

That way if it's ready it returns a good value, if it's not ready it returns None, which would allow the loop to move on to the next reading.

(I'm open to other ideas, I just want to make sure we don't stall or get stuck waiting for the altitude readings.)

**Comment by lo9key** [comment]
Another thought, right now it reads a single register to get the status, then immediately reads the following 3 registers to get the values.

So when we call `pressure()` it stalls on `poll()` until the sensor is ready, then it reads a block of 3 registers, does some math, and returns altitude.  Then we call `altitude()` and it stalls on `poll()` again, reads the exact same block of 3 registers but does different math, and returns pressure.

We can optimize those steps by just reading a block of 4 registers once, and either return None or the correct values for both altitude and pressure.

Or, if this were a class, it could return the last known altitude while waiting for the sensor to prepare a new altitude.  That might or might not be good, hmm.

**Comment by revnak** [comment]
This has been completed
