### ISSUE TITLE
Successfully connect Display to OSU database

### ISSUE THREAD

**Issue by lo9key** [OregonStateRocketry/30k2018-CS-Capstone#9]
- [x] Create database on classmysql
- [x] Copy database tables and contents from primary ground station to OSU database
- [x] Test login credentials on OSU database (via flip or OSU network)
- [x] Successfully connect Display program to OSU database by editing Display/Server/config.yml

database:
    host: classmysql.engr.oregonstate.edu
    user: capstone_group41
    pass: <our db password>
    database: capstone_group41

Or, write your error messages here so we can troubleshoot this.

**Comment by ASladek** [comment]
The database works for testing as long as all fields are filled out correctly.
